import {Request, Response} from 'express'; //importing typescript types for the request and response object of express
import { classroomService } from '../services/instances'; 
export class ClassroomController{
    async create(req: Request, res: Response){ //Request and Response are the datatype, while req and res are the actual parameter names 
        const {classroomName} = req.body; //pull the data out of the request body and saves it in the classroomName
        const result = await classroomService.create(classroomName) //calls the create method on the existing classroomService instance(line 4, the container) which builds a new classroom object(contained) with an autogenerated id and an empty stdList (basically creating a new data) saving the reference of the classroom obj inside the result variable
        return res.status(201).json(result) //returns "201" which is the standard "created" status code along with a parsed result data into json
    }

    async getAll(req:Request, res:Response){
  
        const page = Math.max(1,Number(req.query.page)||1);
        const limit = Math.max(1,Number(req.query.limit) ||3);
        const name = typeof req.query.name === 'string' ? req.query.name : undefined;
        const result = await classroomService.getAll(page, limit, name);//calls the getAll function from the classroomService file
       
        if(!result){
            return res.status(500).json({message:'Internal server error'});
        }
       return res.status(200).json(result);//returns "200" which is the standard "ok" status code

    }

    async getOne (req:Request, res:Response){
        const id= Number(req.params.id); //create a variable called id which accessed the id section of the url using params
        const result = await classroomService.getOne(id); //call the getOne function from the classroomService file
         if (!result){ //checks if the service returns null, meaning no classrooms were matched with the
            return res.status(404).json({message: 'Classroom not found'}); //returns "404" which is the standard "not found" status code
        }
        return res.status(200).json(result); //returns "200" which is the standard "ok" status code
    }

    async update (req:Request, res: Response){
        const id = Number(req.params.id); //create a variable called id which accesses the id section of the url using params
        const classroomName = req.body.classroomName; //create a variable which accesses the data found in the body section and stores it as a string
        const result = await classroomService.update(id,classroomName); //calls the update function from the classroomService file using the new id and classroomName data
        if (!result){ //checks if the service returns null, meaning no classrooms were matched with the id
            return res.status(404).json({message: 'Classroom not found'}); //returns "404" which is the standard "not found" status code
        }
        return res.status(200).json(result);
    }

    async delete (req:Request, res:Response){
        const id = Number(req.params.id) //create a variable called id which accesses the id section of the url using params
        const result = await classroomService.delete(id);//calls the delete function from the classroomService file using the id
        if (!result) //checks if the service returns null, meaning no classrooms were matched with the id
            return res.status(404).json({message:'Classroom not found'});
        return res.status(200).json({message:'classroom deleted successfully'});
    }
}