//this file is used to declare the associations between different classes 
//this file run once at startup and its effict is permanent for the life of the process
import { Classroom } from "./Classroom";
import { User } from "./Users";
import { Course } from "./Course";

//a one-to-many relationship needs 2 declarations one from each side
Classroom.hasMany(User,{foreignKey:'classroomId'})
User.belongsTo(Classroom,{foreignKey:'classroomId'})

//a many-to-many relationship needs 2 declarations one from each side
//StudentCourses is a table name (through:" "), not a model file. sequelize auto-creates/manages the junction table (StudentCourses) with just stdId and courseId (plus its own autogenerated id)

User.belongsToMany(Course,{
    through:'UserCourses',
    foreignKey:'userId',
    otherKey:'courseId'
});
Course.belongsToMany(User,{
    through:'UserCourses',
    foreignKey:'courseId',
    otherKey:'userId'
});

//these associations lst sequelize to automatically generate helper methods which internally handle syncing