import { DataTypes, Model, Optional } from "sequelize";
import sequelize from "../config/database";

interface UserAttributes{
    userId: string;
    userName: string;
    userEmail: string;
    userPassword: string;
    userRole: 'admin' | 'student';
    userPermissions: string | null;
    studentId: number | null;
    studentAge: number | null;
    classroomId: number | null;
}

//the userId is considered optional since its autogenerated similar to the studentId, its never supplied by the user, userPermissions is optional since its a nullable field and is allowed to be empty
interface UserCreationAttributes extends Optional<UserAttributes, 'userId' | 'userPermissions'| 'studentId' | 'studentAge' | 'classroomId'>{} 

export class User extends Model <UserAttributes, UserCreationAttributes> implements UserAttributes{
    public userId!: string;
    public userName!: string;
    public userEmail!: string;
    public userPassword!: string;
    public userRole!: 'admin' | 'student';
    public userPermissions!: string | null;
    public studentId!: number | null;
    public studentAge!: number | null;
    public classroomId!: number | null;
}

User.init(
  {
    userId:{
        type: DataTypes.UUID,
        defaultValue:DataTypes.UUIDV4,
        primaryKey:true,
    },

    userName:{
            type:DataTypes.STRING, 
            allowNull:false,
    },
    userEmail:{
        type:DataTypes.STRING, 
        allowNull:false,
        unique:true,
    },

    userPermissions:{
        type:DataTypes.STRING, 
        allowNull:true,
    },
        
    userPassword: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    
    userRole:{
        type:DataTypes.ENUM('admin', 'student'),
        allowNull:false,
    },  
    
    studentId:{
        type:DataTypes.INTEGER, 
        autoIncrement:true,
        unique:true,
        allowNull:true, 
    },
        
    studentAge:{
        type:DataTypes.INTEGER, 
        allowNull:true,
    },
    
    classroomId:{
        type:DataTypes.INTEGER, 
        allowNull:true, 
    }
    }, 
    {
        sequelize, 
        tableName:'Users'
    }
)
